package others;
// Generated 2017-05-18 18:23:36 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoginHistory generated by hbm2java
 */
@Entity
@Table(name="login_history")
public class LoginHistory implements java.io.Serializable {

    @Id
    @Column(name = "ID_logowania")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer idLogowania;
    @Column(name="ID_user")
    private int idUser;
    @Column(name="Data")
    private Date data;

    public LoginHistory() {
    }

    public LoginHistory(int idUser, Date data) {
        this.idUser = idUser;
        this.data = data;
    }

    public Integer getIdLogowania() {
        return this.idLogowania;
    }

    public void setIdLogowania(Integer idLogowania) {
        this.idLogowania = idLogowania;
    }

    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

}
