package others;
// Generated 2017-05-18 18:23:36 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles")
public class Roles implements java.io.Serializable {

    @Id
    @Column(name="ID_role")
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Integer idRole;
    @Column(name="Type")
    private String type;

    public Roles() {
    }

    public Roles(String type) {
        this.type = type;
    }

    public Integer getIdRole() {
        return this.idRole;
    }

    public void setIdRole(Integer idRole) {
        this.idRole = idRole;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
