package others;
// Generated 2017-05-18 18:23:36 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

    @Id
    @Column(name = "ID_User")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer idUser;
    @Column(name = "Name")
    private String name;
    @Column(name = "Password")
    private String password;
    @Column(name = "ID_Role")
    private int idRole;
    
    private String myRole;

    public Users() {
    }

    public Users(String name, String password, int idRole) {
        this.name = name;
        this.password = password;
        this.idRole = idRole;
        if(this.idRole == 1)
            this.myRole = "ADMIN";
        else
            this.myRole = "USER";
    }

    public String getMyRole() {
        return myRole;
    }
    
    public Integer getIdUser() {
        return this.idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getIdRole() {
        return this.idRole;
    }

    public void setIdRole(int idRole) {
        this.idRole = idRole;
        if(idRole == 1)
            this.myRole = "ADMIN";
        else
            this.myRole = "USER";
    }

    @Override
    public int hashCode() {
            final int prime = 31;
            int result = 1;
            result = prime * result + ((name == null) ? 0 : name.hashCode());
            return result;
    }    
    
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Users other = (Users) obj;
        if (name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!name.equals(other.name)) {
            return false;
        }
        return true;
    }

}
